# Generated by Django 6.0.4 on 2026-05-04 09:52

import members.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_merge_libarian_into_member_and_proxy_librarian'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('objects', members.managers.UserManager()),
            ],
        ),
    ]
